version: "3.9"

services:
    



    ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Pa##w0rd2020"
            MSSQL_PID: Express
        ports:
            - "1433:1433"

    profile-ms:
        image: demonmasks/imagine_profile_ms
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
        ports:
            - "8081:80"
        hostname: profilems
        depends_on:
            - ms-sql-server

    api-gateway:
        image: nisanchezva/api_gateway
        restart: on-failure
        ports:
            - "5000:5000"
        environment:
            - PROFILE_MS_URL=profilems:80
        hostname: apigateway
        depends_on:
            - profilems

    interface:
        image: nisanchezva/imagine_interface
        restart: on-failure
        environment:
            - GRAPHQL_CLIENT_URL=http://apigateway:5000/graphql
            - SERVER_PORT=1111
        ports:
            - "1111:1111"
        depends_on:
            -  apigateway

